### ISSUE TITLE
Enable/Disable button is relying on color alone

### ISSUE THREAD

**Issue by renatoi** [sarbbottam/focus-indicator#13]
For someone with color blindness it would be hard to tell if the extension is enabled or disabled. Please add another visual indicator.

**Comment by sarbbottam** [comment]
Did you mean to customize the icon color?

**Comment by renatoi** [comment]
No, the button to toggle the addon (the one that stays on the right side of the address bar) is relying on color alone to be "active" or "inactive".

**Comment by sarbbottam** [comment]
What do you suggest? What is the expected output?

**Comment by renatoi** [comment]
Not sure, maybe add a "ON" and "OFF" text inside?
