### ISSUE TITLE
Option to show current active element

### ISSUE THREAD

**Issue by AllenReyes** [sarbbottam/focus-indicator#15]
When tabbing through the page, sometimes there are (incorrectly) focusable elements, that are not visible. It would be great to add an option to show the current active element, very useful for debugging.

**Comment by sarbbottam** [comment]
This does not seem to be feasible. As the non-visible focusable item could be hidden via different means, for example `position: absolute; left: -9999px`, or `opacity: 0`, may be the parent container is set to `height: 0; overflow: hidden` etc ...

It would be great to have this feature, but it might be never ending 🐰 hole. 

Open to any suggestions/solutions ...

**Comment by sarbbottam** [comment]
May be ...
- if the focused [node is not visible](https://gist.github.com/jasonfarrell/3659166)
  - clone the node
  - append it to document and highlight
