### ISSUE TITLE
Package for Firefox as well

### ISSUE THREAD

**Issue by jandsu** [sarbbottam/focus-indicator#23]
Hello,

This extension is very useful and works very well... within Chrome ;)

Now that recent Firefox versions have adopted the WebExtension standard, this extension **already works inside Firefox today**, with no single code change!

The only problem is that it is not available in the Mozilla add-on "market".

I checked that it worked by following the first steps of 
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension
(namely "Install your extension in Firefox and test it out.")
Of course, before, I had to clone then `npm install`,  `npm run prebuild` and `npm run build`...

I could publish it myself, but despite the permissive MIT license, I would feel like stealing your work... and then I'd have to watch for any new release in the Chrome Web Store to publish it for Firefox as well...
For those reasons, it seems more natural that the same project owns the publication onto the two browsers "markets".

What do you think about it?

Many thanks in advance and best regards

**Comment by sarbbottam** [comment]
It works for firefox by default, need to publish it.

**Comment by jandsu** [comment]
It works like a charm! Thanks!
For those who would be searching it... https://addons.mozilla.org/en-US/firefox/addon/focus-highlight/
